name: Run tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - run: yarn
      - run: yarn test

